In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
# zomato dataset
df=pd.read_csv(r"C:\Users\rajashekar\OneDrive\Desktop\HAckathon\zomato_data.csv")

In [61]:
df.shape

(51717, 10)

In [62]:
df.head()

,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_costfor_two_people,listed_intype,listed_incity
0,Yes,Yes,4.1/5,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Yes,No,4.1/5,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,Yes,No,3.8/5,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,No,No,3.7/5,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,No,No,3.8/5,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [63]:
df.tail()

,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_costfor_two_people,listed_intype,listed_incity
51712,No,No,3.6 /5,27,Bar,NaN,Continental,"1,500",Pubs and bars,Whitefield
51713,No,No,NaN,0,Bar,NaN,Finger Food,600,Pubs and bars,Whitefield
51714,No,No,NaN,0,Bar,NaN,Finger Food,"2,000",Pubs and bars,Whitefield
51715,No,Yes,4.3 /5,236,Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield
51716,No,No,3.4 /5,13,"Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500",Pubs and bars,Whitefield

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   online_order               51717 non-null  object
 1   book_table                 51717 non-null  object
 2   rate                       43942 non-null  object
 3   votes                      51717 non-null  int64
 4   rest_type                  51490 non-null  object
 5   dish_liked                 23639 non-null  object
 6   cuisines                   51672 non-null  object
 7   approx_costfor_two_people  51371 non-null  object
 8   listed_intype              51717 non-null  object
 9   listed_incity              51717 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.9+ MB

In [65]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [66]:
df.sample(5)

,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_costfor_two_people,listed_intype,listed_incity
6736,No,No,3.7/5,15,"Casual Dining, Bar",NaN,"North Indian, Chinese, Continental","2,000",Pubs and bars,Brigade Road
51591,Yes,No,3.5 /5,51,Quick Bites,NaN,Biryani,300,Dine-out,Whitefield
2516,Yes,No,4.6/5,228,Cafe,"Pizza, Nachos, Garlic Maggi, Burgers, Cheese M...","Cafe, Beverages",400,Cafes,Basavanagudi
2182,No,No,NaN,0,Quick Bites,NaN,Biryani,200,Dine-out,Bannerghatta Road
12292,Yes,No,3.3/5,6,Quick Bites,NaN,"South Indian, Biryani",300,Delivery,Church Street

In [67]:
df

,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_costfor_two_people,listed_intype,listed_incity
0,Yes,Yes,4.1/5,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Yes,No,4.1/5,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,Yes,No,3.8/5,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,No,No,3.7/5,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,No,No,3.8/5,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...
51712,No,No,3.6 /5,27,Bar,NaN,Continental,"1,500",Pubs and bars,Whitefield
51713,No,No,NaN,0,Bar,NaN,Finger Food,600,Pubs and bars,Whitefield
51714,No,No,NaN,0,Bar,NaN,Finger Food,"2,000",Pubs and bars,Whitefield
51715,No,Yes,4.3 /5,236,Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield
51716,No,No,3.4 /5,13,"Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500",Pubs and bars,Whitefield

# Data Cleaning & Preprocessing

### Step 1: Rating Column (rate)

- Replace '-' values with NaN


- Remove /5 and retain only the numeric value


- Convert to float using pd.to_numeric()


- Fill missing values using the median rating

In [68]:
df["rate"]

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
51712    3.6 /5
51713       NaN
51714       NaN
51715    4.3 /5
51716    3.4 /5
Name: rate, Length: 51717, dtype: object

In [69]:
set(df["rate"])

{'-',
 '1.8 /5',
 '1.8/5',
 '2.0 /5',
 '2.0/5',
 '2.1 /5',
 '2.1/5',
 '2.2 /5',
 '2.2/5',
 '2.3 /5',
 '2.3/5',
 '2.4 /5',
 '2.4/5',
 '2.5 /5',
 '2.5/5',
 '2.6 /5',
 '2.6/5',
 '2.7 /5',
 '2.7/5',
 '2.8 /5',
 '2.8/5',
 '2.9 /5',
 '2.9/5',
 '3.0 /5',
 '3.0/5',
 '3.1 /5',
 '3.1/5',
 '3.2 /5',
 '3.2/5',
 '3.3 /5',
 '3.3/5',
 '3.4 /5',
 '3.4/5',
 '3.5 /5',
 '3.5/5',
 '3.6 /5',
 '3.6/5',
 '3.7 /5',
 '3.7/5',
 '3.8 /5',
 '3.8/5',
 '3.9 /5',
 '3.9/5',
 '4.0 /5',
 '4.0/5',
 '4.1 /5',
 '4.1/5',
 '4.2 /5',
 '4.2/5',
 '4.3 /5',
 '4.3/5',
 '4.4 /5',
 '4.4/5',
 '4.5 /5',
 '4.5/5',
 '4.6 /5',
 '4.6/5',
 '4.7 /5',
 '4.7/5',
 '4.8 /5',
 '4.8/5',
 '4.9 /5',
 '4.9/5',
 'NEW',
 nan}

In [70]:
#Replace '-' values with NaN
df["rate"]=df["rate"].replace("-",np.nan)

In [71]:
# removing "NEW"
df["rate"]=df["rate"].str.replace("NEW","")

In [72]:
#Remove /5 and retain only the numeric value
df["rate"]=df["rate"].str.replace("/5","")

In [73]:
#Convert to float using pd.to_numeric()
df["rate"]=pd.to_numeric(df["rate"])
df["rate"].dtype

dtype('float64')

In [74]:
# Fill missing values using the median rating
df["rate"]=df["rate"].fillna(df["rate"].median())
df["rate"].isna().sum()

0

### Step 2: Cost Column (approx_costfor_two_people)

- Remove commas from numeric strings ('1,000' → '1000')


- Convert to numeric


- Fill missing values using the median cost

In [75]:
df["approx_costfor_two_people"]

0          800
1          800
2          800
3          300
4          600
         ...
51712    1,500
51713      600
51714    2,000
51715    2,500
51716    1,500
Name: approx_costfor_two_people, Length: 51717, dtype: object

In [76]:
#Remove commas from numeric strings ('1,000' → '1000')
df["approx_costfor_two_people"]=df["approx_costfor_two_people"].str.replace(",","")

In [77]:
#Convert to numeric
df["approx_costfor_two_people"]=pd.to_numeric(df["approx_costfor_two_people"])
df["approx_costfor_two_people"].dtype

dtype('float64')

In [78]:
#Fill missing values using the median cost
df["approx_costfor_two_people"]=df["approx_costfor_two_people"].fillna(df["approx_costfor_two_people"].median())
df["approx_costfor_two_people"].isna().sum()

0

### Step 3: Categorical Columns

- dish_liked → Replace NaN with "Not Available"


- cuisines → Replace NaN with "Other"


- rest_type → Replace NaN with "Unknown"

In [79]:
set(df["dish_liked"])

{nan,
 'Sandwiches, Chicken Sandwich, Faluda, Egg Sandwich, Salads, Fruit Salad',
 'Masala Dosa, Vada, Set Dosa, Filter Coffee, Raita, Idli Sambar, Bonda',
 'Coffee, Hot Chocolate, Chocolate Muffin, Cappuccino, Sandwiches, Latte, Croissants',
 'Burgers, Pav Bhaji, Paneer Tikka, Salad, Sandwiches, Pasta, Pizza',
 'Paneer Biryani, Calcutta Biryani, Raita, Pot Biryani, Paneer Tikka, Hyderabadi Biryani, Vegetable Biryani',
 'Breakfast Buffet, Chocolate Cake, Mutton Biryani, Salads, Pasta, Chaat, Mushroom Soup',
 'Tandoori Chicken, Coffee, Butter Chicken, Fish Curry, Biryani',
 'Thali, Thepla, Gulab Jamun, Masala Lassi, Rice, Gujarati Food, Roti',
 'Garlic Bread, Peppy Paneer Pizza, Chocolava Cake, Cheese Burst Pizza',
 'Paan Shot, Butter Chicken, Paratha, Veg Platter, Dal Makhani, Aam Panna, Multani Paneer Tikka',
 'Cocktails, Burgers, Nachos, Sandwiches, Butterfly Chicken, Pizza, Dabeli',
 'Hot Coffee',
 'Rice Kheer, Dhaniya Chutney, Rabri, Aloo Paratha, Chole, Cheese Paneer Paratha, Dal Makhani',
 'Hummus Falafel, Gulab Jamun, Shawarma, Bbq Chicken, Mojito, Chicken Biryani, Manchow Soup',
 'Andhra Meal, Potato Wedges, Chicken Biryani, Chicken Satay, Dal Fry',
 'Cocktails, Biryani, Paneer Makhani, Sangria, Tandoori Chicken, Veg Pulao, Tomato Shorba',
 'Rice, Paratha, Thali',
 'Rolls, Tandoori Momos, Soya Chaap, Peri Peri Chicken Roll, Chicken Biryani, Fries, Paneer Roll',
 'Dal Makhani, Thali, Shahi Paneer',
 'Orange Juice, Garlic Naan',
 'Cocktails, Breakfast Buffet, Croissants, Lassi, Caramel Cake, Salads, Waffles',
 'Chicken Fries, Burgers, Thin Crust Pizza, Zinger Burger',
 'Waffles, Vanilla Ice Cream, Hot Chocolate Fudge, Coffee, Brownie, Tiramisu, Chocolava',
 'Paneer Roll, Masala Chai, Masala Tea, Aloo Paratha, Chaat, Brownie Chocolate, Methi Paratha',
 'Pasta, Biryani, Cocktails, Mocktails, Pizza, Nachos, Blueberry Cheesecake',
 'Panneer Butter Masala, Vada, Curd Rice, Idli, Jeera Rice, Naan, Kulcha',
 'Momos, Noodles, Chop Suey',
 'Waffles, Pancakes',
 'Zinger Burger, French Fries, Choco Lash, Hot Wings, Virgin Mojito',
 'Salads, Sandwiches, Shawarma, Watermelon Juice, Tea, Papaya Juice, Fruit Juices',
 'Chicken Teriyaki Bao, Kaffir Lime, Walnut Brownie, Rice Bowls, Khao Suey, Veg Bao, Snapper',
 'Brownie, Mutton Seekh, Salads, Rasmalai, Tandoori Aloo, Mutton Soup, Lunch Buffet',
 'Filter Coffee, Masala Dosa, Pongal, Pav Bhaji, Badam Milk, Thali',
 'Thick Shakes, Chocolate Hazelnut Shake, Mango Shake, Choco Hazelnut, Milk Shake, Chocolate Oreo, Strawberry Milkshake',
 'Vegetable Biryani, Raita, Mutton Biryani, Chicken Kebab Biryani, Paneer Biryani, Chicken Biryani Combo, Lemon Chicken',
 'Momos, Chilli Mushroom, Chop Suey, Sweet Corn Soup, Clear Soup, Hakka Noodles, Honey Chilli Potatoes',
 'Panneer Butter Masala, Manchurian, Fruit Salad, Idli, Filter Coffee, Dhokla, Kashmiri Pulao',
 'Veg Manchow Soup, Garlic Butter Noodle, Chop Suey, Basil Rice, Chicken Dim Sum',
 'Onion Kulcha, Hyderabadi Chicken Dum Biryani, Butter Naan, Veg Seekh Kebab, Mushroom Manchurian, Wings, Mutton Biryani',
 'Burgers, Cocktails, Beef Patty, Chaap, Kulcha, French Fries, Chicken Burger',
 'Chaat, Thali, Jalebi, Rajma, Paneer Tikka, Paratha, Kulfi',
 'Rasgulla, Dal Bati, Rajasthani Thali, Kachori, Churma, Jal-jeera, Rasmalai',
 'Pizza, Lava Cake, Chocolava Cake',
 'Rolls, Biryani, Dum Aloo',
 'Mai Thai, Sangria, Pizza, Cocktails, Biryani, Beer, Chicken Nachos',
 'Biryani, Pepper Chicken',
 'Burgers, Chicken Popcorn, Peri Peri Chicken, Wings, Peri Peri Burger, Fries, Crunchy Veg Burger',
 'Donut, Burgers, Eclair, Hot Chocolate',
 'Lassi, Tandoori Chicken, Paratha, Punjabi Chicken, Aloo Tikki, Butter Chicken, Aam Panna',
 'Chicken Chettinad',
 'Sea Food, Fish, Murgh Ghee Roast, Crabmeat Soup, Jeera Rice, Prawn, Chicken Grill',
 'Chilli Paneer, Hakka Noodles',
 'Lassi, Chai, Paratha',
 'Samosa, Poha, Chaat, Chhole Bhature, Ginger Tea, Chole, Aloo Tikki',
 'Burgers, Beef Burger, Sandwiches, Fries, Bacon Burger',
 'Club Sandwich, Burgers, Basil Chicken, Pasta, Sandwiches, Mojito, Fries',
 'Manchow Soup, Shawarma, Momos, Hyderabadi Biryani, Vegetarian, Noodles, Dragon Chicken',
 'Buttermilk, Chicken Biryani, Lassi, Tandoori Chicken, Bamboo Biryani, Mutton Biryani, Vegetable Biryani',
 'Marshmallow, Chocolate Waffles',
 'Chicken Masala Biryani, Kulcha, Raita, Chicken Nihari, Shami Kebab, Shahi Tukda, Mutton Biryani',
 'Salads, Mint Masala, Breakfast Buffet, Pasta, Spring Roll, Lunch Buffet, Roti',
 'Steak, Pizza, Burgers, Pasta, Fish, Wedges, Onion Rings',
 'Coffee, Cappuccino',
 'Burgers, Pasta, Caramel Custard, Carbonara, Crispy Corn, Mutton Curry, Lemonade',
 'Rolls, Momos, Paneer Roll, Veggie Roll',
 'Appam, Chicken Biryani, Kizhi Biryani, Kuluki Sarbat, Panneer Butter Masala, Meen Pollichathu, Vellarikka Pattanam',
 'Hyderabadi Style Biryani, Tandoori Chicken, Mutton Biryani, Vegetable Biryani, Dum Biryani, Chicken Boneless Biryani, Lemon Chicken',
 'Filter Coffee, Mini Idlis',
 'Sandwiches, Burgers, Lamb Burger, Chicken Pepper Steak, Club Sandwich, Draught Beer, Hot Dog',
 'Cheesy Maxx Pizza, Pasta, Cheesy Garlic Bread, Pane Pizza, Kurkure Pizza',
 'Burgers, Macaroon, Eclair, Coffee, Sandwich, Fries, Hot Chocolate',
 'Chicken Grill, Biryani',
 'Chole, Kulfi, Kachori, Samosa, Chaat, Pav Bhaji, Barfi',
 'Radhaballavi, Egg Noodles, Egg Roll, Egg Devils, Alur Dom',
 'Badam Milk, Kulfi, Rasmalai, Rasgulla',
 'Appam, Chicken Biryani, Butter Naan',
 'Vegetarian',
 'Chicken Lollipop, Dragon Rolls, Pasta Alfredo, Chicken Pakora, Burgers, Cappuccino, Chicken Wings',
 'Filter Coffee, Tea, Hot Coffee, Hatti Samosa',
 'Waffles, Oreo Shake, Banana Nutella Crepe',
 'Stuffed Chicken, Malai Broccoli, Cocktails, Salad, Mocktails, Tomato Soup, Biryani',
 'Dum Biryani, Fiery Chicken, Butter Chicken, Pepper Chicken, Paneer Tikka Masala, Chicken Grill, Corn Paratha',
 'Kheer, Lassi, Paratha, Amritsari Kulcha, Dal Makhani, Chole Bhature, Aloo Kulcha',
 'Turkish Ice Cream, Baklava, Chocolate Icecreams',
 'Lassi, Bhindi Masala, Chicken Butter Masala, Dal Makhani, Achari Paneer, Chicken Bharta, Malai Kofta',
 'Spicy Crispy Corn, Mocktails, Chicken Wings, Pasta, Virgin Mojito, Pizza, Blueberry Mojito',
 'Buddha Bowl, Chicken Curry, Brownie, Chole, Veg Thali, Idli, Raita',
 'Mutton Mandi, Laccha Paratha, Mutton Nihari, Chicken Curry, Tawa Chicken, Rabri, Raan',
 'Pav Bhaji, Vada Pav, Panipuri, Tea, Samosa Chaat, Bhel Puri, Jalebi',
 'Nachos, Chocolate Waffles, Nutella Waffle, Salsa, Oreo Waffle',
 'Cocktails, Beer, Mocktails, Biryani, Long Island Iced Tea, Drunken Prawn, Sunday Brunch',
 'Dal Makhani, Butter Chicken, Tandoori Momos',
 'Stuffed Mushroom, Chicken Biryani, Jal-jeera',
 'Pizza Burger, Garlic Bread, Chocolava',
 'Butter Naan, Paratha, Kulcha, Butter Chicken, Shawarma, Roti, Thali',
 'Manchow Soup, Dragon Rolls, Crispy Spinach Chicken, Thread Chicken, Chop Suey, American Chopsuey, Honey Chilli Chicken',
 'Kharabath, Crispy Vada, Filter Coffee, Idli Vada, Idli Chutney, Kesari Bath, Gulab Jamun',
 'Paratha, Panipuri, Puri Sabzi, Rasgulla, Rasmalai, Pav Bhaji, Samosa Chaat',
 'Chilli Babycorn, Egg Chilli, Chicken Curry, Palak Paneer, Sweet Lassi, Chaach, Butter Chicken',
 'Sandwiches, Pasta, Pizza',
 'Waffles, Red Velvet Waffle, Brownie Sundae, Nutella Waffle',
 'Rolls, Momos, Masala Fries, Kulfi, French Fries, Egg Roll, Paneer Roll',
 'Churros, Empanadas, Hot Chocolate, Chocolate Banana, Salad, Chocolate Shake, Patata Bravas',
 'Chicken Momo, Chicken Sizzler, Chocolate Momos, Momo Burger, Burgers, Veg Momos, Corn Momo',
 'Beer, Burgers, Sandwiches, Virgin Mojito, Beef Chilli, Pork Chilli, Nachos',
 'Filter Coffee, Crab Soup, Fish, Fried Rice',
 'Coffee, Pasta, Burgers, Chocolate Milkshake, Spaghetti, Sandwich, Pancakes',
 'Garlic Bread, Cheese Burst Pizza, Meat Eater Pizza',
 'Butter Chicken, Shawarma Roll, Chicken Shawarama, Chicken Grill, Rolls, Al Faham Chicken, Biryani',
 'Paratha, Pasta',
 'Ice Cream Sundae, Fruit Salad, Hot Chocolate Fudge, Brownie, Chocolate Mousse, Chocolate Icecreams, Almond Fudge',
 'Masala Dosa, Filter Coffee, Tea, Onion Dosa, Vada Sambar, Badam Milk, Badam Halwa',
 'Fish Curry, Appam, Kerala Parotta, Paratha, Beer, Kadala Curry, Sea Food',
 'Dal Kichadi, Gulab Jamun, Buttermilk, Aamras, Grand Thali, Dhokla, Jalebi',
 'Veggie Pizza, Garlic Bread, Lava Cake, Chocolava, Spicy Paneer',
 'Beer, Pasta, Burgers, Biryani, Masala Peanuts, Noodles, Au Gratin',
 'Chicken Cheese Sandwich, Cheese Sandwiches, Chocolate Sandwich, Chocolate Sandwiches, French Fries, Teriyaki Chicken',
 'Bbq Chicken Pizza, Cocktails, Sangria, Beer, Chicken Nachos, Mai Thai, Burgers',
 'Cocktails, Badam Milk, Mutton Liver Fry, Neer Dosa, Paan Mojito, Veg Thali, Mocktails',
 'Vada, Kesari Bath, Filter Coffee',
 'Dal Makhani, Biryani, Sandwiches, Salad, Gulab Jamun, Sandwich, Brownie Chocolate',
 'Mutton Biryani, Thali',
 'Mutton Biryani, Pahari Chicken, Chicken Biryani, Mutton Chops, Mutton Roganjosh, Shawarma, Raita',
 'Coffee, Dahi Vada, Chaat',
 'Sushi, Kimchi, Pork Sizzler, Chicken Donburi, Shrimp Donburi, Crab Roll, Bulgogi',
 'Breakfast Buffet, Paratha, Rice',
 'Veggie Delight, Paneer Tikka, Salad',
 'Butter Chicken, Beer, Vegetable Biryani, Kulfi, Cocktails, Chur Chur Paratha, Keema Pav',
 'Thali, Filter Coffee, Vada, Rava Idli, Masala Dosa, Stuffed Kulcha, Naan',
 'Chicken Biryani, Vegetable Biryani, Raita',
 'Filter Coffee, Pizza, Pasta',
 'Pizza, Rolls, Burgers',
 'Fruit Cake, Blueberry Cake, Brownie, Chocolate Walnut Cake, Carrot Cake, Chocolate Blueberry, Meetha Paan',
 'Cocktails, Burgers, Chicken Chunks, Crispy Chicken',
 'Pasta, Salads, Mocktails, Veg Buffet, Paneer Tikka, Biryani, Falafel',
 'Noodles, Momos',
 'Mutton Biryani, Stuffed Mushroom, Onion Pakoda, French Fries, Paneer Pakora, Afghani Kebab',
 'Chocolate Truffle Cake, Eggless Cake, Cup Cake, Chocolate Dreamcake, Photo Cake, Fruit Cake, Litchi Cake',
 'Pasta, Coffee, Buffalo Chicken Wings, Caesar Salad, Cheesy Fries, Mojito, Salads',
 'Coffee, Chai, Idli, Pav Bhaji, Vada, Tea, Masala Dosa',
 'Dragon Chicken, Salad, Hakka Noodles, Chicken Momo, Chop Suey, Dragon Rolls, Fish Chilli',
 'Masala Dosa, Coffee, Pongal, Tea, Bonda',
 'Tandoori Chicken, Dal Makhani, Butter Chicken, Roti, Veg Thali',
 'Sea Food, Neer Dosa, Crab Ghee Roast, Jumbo Prawns, Thali, Crab Butter, Crab Masala',
 'Paneer Picante Pizza, Chicken Salami, Peri Peri Pizza, Veggie Pizza',
 'Cocktails, Pizza, Fries, Pasta, Chicken Sizzler, Mocktails, Long Island Iced Tea',
 'Bhatti Chicken, Chole, Shahi Tukda',
 'Corn Balls, Cocktails, Mocktails, Sunday Brunch, Fish, Tikka, Chicken Wings',
 'Burgers, Nachos, Oreo Shake, Veg Sandwich, Veg Burger',
 'Raita, Chicken Biryani',
 'Chilli Paneer Pizza, Mocktails, French Fries, White Sauce Pasta, Nachos, Manchurian',
 'Momos, Rice Noodles, Kung Pao Chicken, Noodle, Rice Bowl, Thai Green Curry, Chicken Dim Sum',
 'Filter Coffee, Masala Dosa, Chilli Babycorn, Pav Bhaji, Pongal, Rava Dosa, Paneer Tikka',
 'Burgers, Sandwiches, Fries, Pasta, Tea, Chicken Curry, Fried Rice',
 'Chicken Kebab, Biryani, Masala Tikka, Chicken Tikka',
 'Chips, Cocktails, Veg Platter, Steak, Murgh Platter, Draught Beer, Long Island Iced Tea',
 'Egg Noodles, Biryani',
 'Cocktails, Khao Suey, Mocktails, Salad, Malacca Curry, Beer, Sangria',
 'Choco Fudge Brownie, Sandwich, Tiramisu, Vanilla Ice Cream',
 'Breakfast Buffet, Biryani, Salads, Chocolate Cake, Pasta, Paneer Tikka, Mushroom Soup',
 'Lunch Buffet, Kheer, Rajasthani Thali',
 'Sandwich',
 'Lemon Rice',
 'Cocktails, Peri Peri Chicken, Beer, Pasta, Nachos, Pizza, Potato Mash',
 'Cocktails, Tandoori Chicken, Paneer Tikka, Stuffed Mushroom, Pasta Alfredo, Mocktails, Salads',
 'Pasta, Pizza, Garlic Bread, Ravioli, Orange Mojito, Chicken Calzone, Mocktails',
 'Pizza, Fish, Cocktails, Cosmopolitan, Pasta Alfredo, Brownie Chocolate, Potli Biryani',
 'Sandwiches, Rose Faluda, Pizza, Custard Apple Cream, Pav Bhaji',
 'Chicken Curry, Chicken Biryani, Jeera Rice, Paneer Biryani, Ghee Rice, Roti, Aloo Matar',
 'Hot Chocolate, Waffles, Chicken Pizza, Brownie, Tea, Chocolate Cupcake, Pasta',
 'Sandwiches, Blueberry Waffles, Fruit Pancake, Blueberry Pancakes, Belgian Waffles, Chocolate Chip Waffle, Banana Caramel',
 'Chicken Kebab, Butter Chicken, Papdi Chaat, Pizza, Dahipuri, Cocktails, Rice Kheer',
 'Malai Kofta, Sandwich, Naan',
 'Salad, Apple Tart, Salads, Vada, Idli, Dhokla, Pasta',
 'Rava Idli, Tea, Coffee, Rava Dosa, Biryani, Masala Dosa, Pav Bhaji',
 'Chocolava',
 'Sandwich, Salads, Pizza, Sandwiches, Salad, Pasta, Fish',
 'Panipuri, Samosa, Rasmalai',
 'Paratha, Kheer, Burgers, Ghee Rice, Rolls, Veg Burger, White Sauce Pasta',
 'Butter Chicken, Shawarma, Chicken Biryani, Vegetable Biryani, Babycorn Manchurian, Dum Biryani, Noodles',
 'Chips, Ferrero Rocher, Vanilla Ice Cream',
 'Butterscotch Ice Cream, Sandwiches, Milk Shake, Hot Chocolate Fudge, Brownie, Vanilla Ice Cream, Burgers',
 'Noodles, Kaffir Lime, Spring Roll, Long Island Iced Tea, Yellow Thai Curry, Vanilla Ice Cream, Jasmine Rice',
 'Butter Chicken, Paneer Methi Malai, Lassi, Butter Naan, Sarso Da Saag, Tandoori Chicken, Gajar Ka Halwa',
 'Cheesy Pizza, Cheese Pasta, Brownie Milkshake, Peri Peri Chicken, Steak, Nachos, Omelette',
 'Fish Chilli, Kadhai Paneer, Vegetable Biryani, Chicken Kebab, Veg Thali, Chicken Butter Masala, Butter Naan',
 'Mojito, Pasta, Bbq Chicken Pizza, Butter Chicken Pizza, Farmhouse Pizza, Ricotta Ravioli, Roast Chicken Pizza',
 'Panipuri, Paratha, Badam Milk, Chaat, Chole Bhature, Raj Kachori, Rasmalai',
 'Appam, Kerala Parotta, Sea Food, Idiyappam, Chicken Chettinad, Dum Biryani, Egg Curry',
 'Potato Mash, Sizzler Brownie, Steak, Pasta, Caramel Custard, Spicy Chicken Sizzler, Spaghetti',
 'Tandoori Chicken, Chicken Boneless Biryani, Paneer Biryani',
 'Cocktails, Mocktails, Momos, Chilli Chicken, Crispy Corn, Nachos, Mojito',
 'Coffee, Cocktails, Tiramisu, Cappuccino, Hot Chocolate, Tea',
 'Raita, Tandoori Chicken, Egg Chilli, Hakka Noodles, Chicken Taka Tak, Palak Paneer, Veg Pulao',
 'Mocktails, Masala Pizza, Salad, Cocktails, Wine, Chilli Chicken, Chicken Tikka',
 'English Breakfast, Burgers, Sandwiches, Chicken Burger, Pasta, Veg Burger, Chicken Sausages',
 'Burgers, Steak, Buffalo Wings, Chicken Wings, Nachos, Chicken Sizzler, Grilled Basa',
 'Lassi, Cheese Balls, Paneer Pakora, Chaach, Buttermilk, Thali, Masala Fries',
 'Coffee, Tomato Soup, Thali, Vada Sambar, Biryani',
 'Prawn, French Fries, Draught Beer, Biryani',
 'Tea, Tomato Rice, Filter Coffee, Idli, Biryani',
 'Lassi, Hyderabadi Biryani, Tandoori Chicken, Lemon Chicken, Chicken Dum Biryani, Prawn Biryani, Boneless Biryani',
 'Virgin Mojito, Pasta Alfredo, Mocktails, Mutton Boti Kebab, Diwani Handi, Chelo Kebab, Dragon Rolls',
 'Chicken Curry, Akki Rottis, Pork Curry, Chilli Pork, Roti, Neer Dosa',
 'Chicken Grill, Rose Milk, Pulpy Grape Juice, Shawarma Roll, Chicken Wings, Rolls, Butter Chicken',
 'Appam, Khao Suey, Rabri, Chicken Biryani, Kebab Platter, Prawn, Pad Thai',
 'Manchurian, Noodles, Basil Chicken, Chop Suey, Triple Schezwan, Dragon Chicken, Schezwan Rice',
 'Steak, Burgers, Meatballs, Apple Pie, Salads, Bruschettas, Chicken Sizzler',
 'Sandwich, Pasta, Sandwiches, Brownie',
 'Salads, Cocktails, Hazelnut Cake, Pepperoni Pizza, Mocktails, Calamari, Risotto',
 'Pasta, Pepperoni, Garlic Bread, Supreme Pizza, Pane Pizza',
 'Ginger Tea, Poha, Paratha, Chai, Chaai',
 'Lunch Buffet, Breakfast Buffet, Salads, Chips, Pasta, Omelette',
 'Ulavacharu, Biryani, Bangla Kodi, Rajugari Kodi Pulao, Curd Rice, Gadwal Kodi Pulao, Fish',
 'Chicken Masala, Butter Naan, Shaadi Ki Biryani, Chicken Shawarama, Mutton Curry, Chicken Grill, Chicken Satay',
 'Dal Makhani, Chicken Curry, Sandwiches, Paratha, Butter Chicken',
 'Paratha, Tikka, Rajma, Sweet Lassi, Murgh Patiala, Paneer Lababdar, Dal Makhani',
 'Thali, Chilli Chicken, Chicken Curry, Andhra Meal, Vegetable Biryani',
 'Pandi Curry, Tender Coconut Pudding, Chocolate Mousse, Ghee Rice, Pork Curry, Bella Coffee, Chicken Curry',
 'Butter Chicken, Murgh Khurchan, Naan, Kulcha, Tandoori Roti, Mutton Biryani, Rice',
 'Biryani, Tandoori Chicken',
 'Chicken Kebab',
 'Mocktails, Pasta, Wood Fire Pizza, Paneer Malai Tikka, French Fries, Nachos, Burgers',
 'Non Veg Thali, Biryani, Ghee Rice',
 'Chicken Guntur, Andhra Meal, Hyderabadi Chicken Biryani, Butter Naan, Andhra Thali',
 'Mutton Biryani, Drunken Chicken, Chicken Biryani, Beer, Cocktails, Pasta, Onion Rings',
 'Chocolava, Nutella Brownie, Ferrero Rocher, Hot Chocolate Fudge',
 'Pasta, Mutton Seekh, Fish, Prawn Curry, Pizza, Papdi Chaat, Salad',
 'Lassi, Mushroom Masala, Chaach, Aloo Paratha, Chole Kulcha, Kadai Paneer, Buttermilk',
 'Paratha, Thali, Rajma, Poha',
 'Lassi, Chole, Palak Paneer, Chaap, Paneer Tikka, Panneer Butter Masala, Paratha',
 'Momos, Chilli Chicken, Sweet Corn Chicken Soup, Wonton Soup, Crispy Noodle, Chicken Garlic Noodle',
 'Buttermilk, Thali, Dal Bati, Panneer Butter Masala, Rajma Rice, Sweet Lassi, Kadhi',
 'Appam, Chicken Biryani, Kuluki Sarbat, Panneer Butter Masala, Meen Pollichathu, Vellarikka Pattanam, Sea Food',
 'Pizza, Waffles, Roti, Pasta, Sushi, Salads, Fish',
 'Salads, Gulab Jamun, Pasta, Fish, Rasgulla, Coffee, Lunch Buffet',
 'Murgh Ghee Roast, Mutton Biryani, Buttermilk, Andhra Meal, Thali, Chilli Chicken, Prawn',
 'Rava Idli, Benne Masala Dosa, Filter Coffee, Tea, Pav Bhaji, Pongal, Curd Vadai',
 'Chicken Manchow Soup, Hunan Chicken, Hakka Noodles, Momos, Prawn, Spring Roll, Crabmeat Soup',
 'Cocktails, Chicken Satay, Sunday Brunch',
 'Pasta, Salads, Cheesy Garlic Bread, Mint Mojito, Chicken Salad, Veg Extravaganza Pizza, Pane Pizza',
 'Cocktails, Badam Milk, Mutton Liver Fry, Paan Mojito, Neer Dosa, Veg Thali, Mocktails',
 'Burgers, French Fries',
 'Shawarma, Rolls',
 'Sandwiches, Chocolava, Salads, Rajma, Halwa, Biryani, Chicken Curry',
 'Sea Food, Spicy Crab Soup, Cocktails, Squid Fry, Prawn Curry, Lobster, Fish Curry',
 'English Breakfast, Sandwiches',
 'Pepperoni Pizza',
 'Cocktails, Mocktails, Mai Thai, Murgh Platter, Pizza, Soya Chaap, Keema Samosa',
 'Fries, Ice Cream Roll, Coffee, Brownie',
 'Tandoori Broccoli, Dal Makhani, Tamatar Ka Shorba, Kadhai Paneer, Raan, Kulfi, Biryani',
 'Coffee, Wedges, Broccoli Soup, Chicken Ceaser Salad, Chicken Burger, Pancakes, Chicken Steak',
 'Pizza, Momos, Pasta, Brownie, Nachos, Hot Chocolate, Waffles',
 'Brownie Chocolate, Manchow Soup, Jalebi, Rabri, Beer, Paneer Tikka, Tandoori Chicken',
 'Coffee, Salad, Club Sandwiches, Pasta, Sandwich, Burgers, Cappuccino',
 'Chaat, Rasmalai, Motichoor Ladoo, Thali, Pav Bhaji, Paneer Tikka, Chole Bhature',
 'Pasta, Momos, Mezze Platter, Pizza, Waffles, Chocolate Milkshake, Peri Chicken',
 'Biryani, Gulab Jamun, Raita',
 'Burgers, Fries, Bbq Chicken Pizza, Pasta, Potato Wedges, Peri Peri Chicken, Steak',
 'Pasta, Sandwiches, Veg Burger, Tea, Coffee, Club Sandwich, French Fries',
 'Phirni, Butter Naan, Kadhai Paneer, Tandoori Roti, Paratha, Dal Makhani, Paneer Tikka',
 'Gulab Jamun, Raita, Paneer Biryani, Mutton Biryani, Buttermilk, Gosht Biryani, Basmati Rice',
 'Burgers, French Fries, Chicken Burger',
 'Pasta, Salads, Chole, Butter Chicken, Brownie, Butter Cookies, Sandwiches',
 'Fries, Whole Meat Shawarma',
 'Sandwiches, Pasta, Poha, Fruit Parfait',
 'Chicken Chettinad, Donne Biryani, Chicken Guntur, Veg Thali, Gobi Tikka, Mutton Chops, Chicken Curry',
 'Podi Idli, Masala Dosa, Pongal, Coffee, Mini Idlis, Appam, Raagi Dosa',
 'Tea',
 'Noodles, Watermelon Mint Mojito, Rendang Curry, Laksa, Momos, Dimsum Platter, Mocktails',
 'Wine, Dumplings, Set Menu, Chicken Dim Sum, Tom Kha Soup, Prawn Crackers, Fish',
 'Kulcha, Cocktails, Peri Peri Chicken, Masala Peanuts, Virgin Colada, Apple Pie, Sea Food',
 'Masala Dosa, Vada, Upma, Filter Coffee, Kesari Bath, Idli Chutney, Kharabath',
 'Basil Chicken, Lunch Buffet, Chicken Tom Yum Soup, Sweet Corn Soup, Singapore Noodles, Chicken Dim Sum, Chicken Wings',
 'Zinger Burger, Crispy Chicken, Rice Bowl, Hot Wings, Pizza, Chicken Popcorn, Virgin Mojito',

In [80]:
#dish_liked → Replace NaN with "Not Available"
df["dish_liked"]=df["dish_liked"].replace(np.nan,"Not Available")
df["dish_liked"].isna().sum()

0

In [81]:
set(df["cuisines"])

{nan,
 'French, Italian',
 'Continental, North Indian, Desserts, Beverages',
 'BBQ, Arabian, Chinese, Kebab, Beverages',
 'North Indian, South Indian, Chinese, Continental, Italian',
 'North Indian, South Indian, Andhra, Continental',
 'Tibetan',
 'Cafe, Continental, Healthy Food, Sandwich, Pizza, Desserts, Beverages',
 'Cafe, Continental, Fast Food, Pizza, Italian, Burger, Chinese, Desserts',
 'Desserts, Cafe, Continental',
 'South Indian, North Indian, Fast Food, Chinese, Street Food',
 'Pizza, Sandwich, Burger, Fast Food',
 'Mughlai, Chinese, Kebab',
 'Fast Food, Beverages, Sandwich',
 'Cafe, Continental, Italian, Burger, Pizza, Salad, Steak',
 'North Indian, Continental',
 'North Indian, Continental, Chinese, Asian, Thai',
 'Desserts, Beverages, American',
 'Chinese, Thai, Seafood, Momos',
 'North Indian, Fast Food, Burger, Momos',
 'Continental, Biryani, Italian, North Indian, Chinese',
 'Thai',
 'Oriya, Chinese, North Indian',
 'Cafe, American, Salad, Continental, Healthy Food, Italian, Coffee, Desserts',
 'North Indian, Chinese, Andhra',
 'South Indian, Biryani, Seafood',
 'Cafe, Continental, Italian',
 'Fast Food, North Indian, Rolls',
 'Italian, North Indian',
 'South Indian, Andhra',
 'North Indian, South Indian, Chinese, Pizza',
 'North Indian, Chinese, Rajasthani',
 'Rolls, North Indian, Mughlai',
 'North Indian, South Indian, Oriya',
 'Continental, Asian, Italian',
 'North Indian, Andhra, Chinese',
 'Cafe, Sandwich, Fast Food, Beverages, Desserts',
 'North Indian, Arabian, Mughlai, Middle Eastern, Grill',
 'Continental, Cafe, Desserts, Salad, Momos',
 'Mediterranean, Arabian, Lebanese',
 'Chinese, Nepalese, Tibetan, Momos',
 'South Indian, Rajasthani',
 'North Indian, Fast Food, Chinese',
 'North Indian, Fast Food, Burger',
 'North Indian, Chinese, Seafood',
 'Andhra, South Indian, Chettinad',
 'South Indian, North Indian, Fast Food, Chinese',
 'Kerala, South Indian, Seafood',
 'Desserts, Street Food, Mithai',
 'American, Continental, BBQ, Steak',
 'North Indian, Mughlai, South Indian, Chinese',
 'North Indian, Kebab, Biryani, Rolls',
 'Cafe, Italian, Tex-Mex, Fast Food, Burger',
 'Beverages, Fast Food, Burger',
 'North Indian, Chinese, Rolls, Biryani, Kebab',
 'Bar Food',
 'Kerala, Biryani, Chinese, North Indian',
 'Kerala, Seafood, Chinese, Biryani, Juices',
 'North Indian, Street Food, Pizza',
 'Pizza, Momos',
 'Sandwich, Salad, North Indian, Chinese',
 'Continental, Finger Food, Asian, North Indian',
 'Healthy Food, Salad, Mexican, Beverages',
 'Continental, South Indian, Finger Food, Pizza, Seafood',
 'Chinese, Thai, Indonesian',
 'Lucknowi, Kebab, Rolls',
 'Sandwich',
 'Beverages, Fast Food, Desserts',
 'North Indian, Chinese, Biryani, Fast Food',
 'Fast Food, North Indian',
 'Biryani, South Indian, Chinese, North Indian, Arabian, Hyderabadi',
 'Middle Eastern, Fast Food, Rolls',
 'Tea, Beverages',
 'Modern Indian, European, American',
 'Healthy Food, Continental, Juices, Salad, Burger, Beverages, Desserts',
 'Chinese, Arabian, Rolls',
 'Cafe, Continental, American, Beverages',
 'Mithai, Street Food, Fast Food',
 'Biryani, Kerala',
 'Chinese, Continental, Burger, Pizza',
 'South Indian, Fast Food, Chinese, North Indian, Street Food',
 'Biryani, Fast Food, Cafe, Coffee, Rolls, Wraps',
 'Arabian, Sandwich, Rolls, Burger',
 'Chinese, Tibetan, North Indian',
 'Andhra, North Indian, Chinese, Biryani, Seafood',
 'Kerala, North Indian, Chinese, Kebab',
 'Mughlai, Biryani, Fast Food',
 'South Indian, Chettinad, Kerala, Seafood',
 'Bakery, Mithai',
 'Kerala, Biryani, South Indian',
 'Cafe, Continental, North Eastern, Chinese, Fast Food',
 'Russian, Continental, North Indian',
 'Continental, North Indian, Pizza, Italian',
 'Seafood, Mangalorean, South Indian',
 'Cafe, Street Food',
 'Thai, Chinese, Indonesian, Asian, Momos',
 'Continental, American, Chinese, BBQ, Salad, Italian',
 'Bengali, Bihari',
 'Asian, Continental, European, North Indian, Mediterranean',
 'Seafood, North Indian, Chinese',
 'Biryani, South Indian, Fast Food, Rolls, Kebab, North Indian',
 'North Indian, Italian',
 'Beverages, North Indian, Chinese, Italian',
 'Biryani, South Indian, North Indian',
 'Tamil, South Indian',
 'Seafood, North Indian, Chinese, Andhra, Biryani, Kebab',
 'North Indian, Chinese, Arabian, Biryani, Fast Food',
 'Biryani, North Indian, Chinese, Andhra',
 'North Indian, Chinese, Continental, Momos',
 'Cafe, Fast Food, Sandwich, Pizza',
 'South Indian, Andhra, Biryani',
 'South Indian',
 'Biryani, Chinese, Kebab',
 'Seafood, South Indian, Chinese',
 'Rolls, Sandwich',
 'Fast Food, North Indian, Chinese, Biryani',
 'South Indian, Chinese, Fast Food',
 'South Indian, North Indian, Fast Food, Street Food',
 'North Indian, Street Food, Pizza, Burger, Sandwich',
 'Thai, Chinese',
 'Burger, Juices, Beverages, Fast Food, Cafe, Chinese, Coffee',
 'Cafe, Rolls, Fast Food',
 'South Indian, North Indian, Chinese, Bakery, Desserts',
 'Chinese, North Indian, Biryani',
 'Biryani, Hyderabadi, North Indian',
 'North Indian, Kebab, Chinese, Fast Food',
 'Rolls, Kebab',
 'Mangalorean, Seafood, North Indian, Chinese',
 'Tea',
 'North Indian, Chinese, South Indian, Juices',
 'Andhra, North Indian, Chinese, Mangalorean',
 'Sandwich, Fast Food, Momos',
 'Chinese, Rolls, South Indian',
 'Kerala, Biryani, South Indian, North Indian, Chinese, Seafood, Juices',
 'North Indian, South Indian, Maharashtrian',
 'North Indian, Chinese, Biryani, Andhra',
 'BBQ, Continental, North Indian, Chinese, Beverages',
 'Japanese, Thai, Chinese, Korean',
 'American, Continental',
 'American, Continental, Salad, Italian',
 'Biryani, North Indian, Chinese, Kerala',
 'Arabian, Mughlai, Chinese, Kebab, Fast Food',
 'North Indian, Arabian, South Indian, Chinese',
 'Asian, Malaysian, Chinese, Thai, Momos',
 'North Indian, Italian, South Indian',
 'Italian, Mexican, Continental, Pizza',
 'North Indian, Chinese, Middle Eastern',
 'North Indian, Chinese, Japanese, European, Seafood',
 'South Indian, Chinese, Kerala',
 'Cafe, Continental, Pizza, Italian, Beverages',
 'South Indian, Andhra, Chinese, North Indian',
 'Mithai, Oriya, Bengali',
 'Cafe, American, Burger, Beverages',
 'Continental, North Indian, Chinese, Finger Food',
 'Seafood, Chinese, South Indian, North Indian',
 'Biryani, Kebab, Continental',
 'Finger Food, North Indian, Chinese, Italian',
 'Burger, Sandwich, Beverages',
 'Kerala, North Indian, Chinese, Arabian',
 'Mughlai, Chinese',
 'Cafe, French, North Indian',
 'Chinese, Thai, Vietnamese',
 'North Indian, Continental, Chinese',
 'Andhra, Hyderabadi',
 'Continental, Italian, North Indian',
 'Continental, Chinese, North Indian',
 'Tibetan, Nepalese',
 'Kerala, Coffee',
 'Roast Chicken, Burger',
 'South Indian, North Indian, Chinese, Street Food, Fast Food',
 'Cafe, American, Burger',
 'Beverages, Juices, Street Food',
 'Biryani, North Indian, Chinese, Seafood',
 'Fast Food, Maharashtrian, Rolls',
 'American, North Indian, Pizza, Finger Food, Continental, Italian',
 'Kerala, North Indian',
 'Tibetan, Asian, Thai, Chinese, Momos',
 'Cafe, Continental, Beverages, Desserts',
 'Malaysian, Thai, Singaporean, Asian, Chinese, Momos',
 'Burger, Sandwich, Fast Food',
 'Bengali, Chinese, Rolls',
 'Chinese, North Indian, Salad, Fast Food',
 'Andhra, Beverages, Biryani, Chinese, Fast Food, Hyderabadi, North Indian, South Indian',
 'Fast Food, Sandwich',
 'Maharashtrian, Street Food',
 'Chinese, Asian, Cantonese, Tea',
 'Andhra, North Indian, Biryani, Beverages',
 'Biryani, North Indian, Mughlai',
 'Italian, American, Pizza',
 'European, Continental',
 'Biryani, Chinese, Kebab, Kerala, North Indian',
 'Cafe, Bakery',
 'Cafe, Italian, Mexican, Chinese',
 'North Indian, South Indian, Chinese, Hyderabadi',
 'North Indian, Kerala, Biryani, South Indian',
 'Chinese, Continental, North Indian, Italian, Seafood',
 'Desserts, Street Food',
 'Fast Food, Hyderabadi',
 'Street Food, Chinese, Italian, North Indian',
 'North Indian, Kerala, Chinese',
 'Biryani, Chinese, South Indian, North Indian',
 'Mediterranean, Italian, Mexican',
 'Mughlai, North Indian, Biryani, Chinese',
 'Pizza, Fast Food, Desserts',
 'Chinese, Asian, Japanese',
 'Andhra, Chinese, North Indian, South Indian',
 'Cafe, Continental, Mediterranean, Italian, Desserts',
 'Japanese, Asian',
 'Fast Food, Burger, Beverages, Cafe, Desserts',
 'North Indian, Bengali, Chinese',
 'Konkan, Seafood',
 'Chinese, North Indian, Thai',
 'North Indian, South Indian, Kerala',
 'Beverages, Healthy Food',
 'Hyderabadi, Biryani, South Indian, Andhra, Beverages',
 'Cafe, Continental, North Indian, Bakery, Desserts',
 'North Indian, Andhra',
 'North Indian, Sindhi, Seafood',
 'South Indian, North Indian, Chinese, Desserts, Juices',
 'North Indian, Biryani, Chinese, Mughlai',
 'Maharashtrian, North Indian',
 'South Indian, Chettinad, Chinese',
 'North Indian, Iranian',
 'North Indian, Finger Food, Chinese',
 'Pizza, Italian, Desserts',
 'Mughlai, Kebab, Biryani',
 'Bakery, Beverages',
 'Chinese, Italian',
 'North Indian, Arabian, Beverages',
 'Fast Food, Italian, North Indian, Steak',
 'Biryani, Mughlai, Chinese, North Indian, Kebab',
 'BBQ, Fast Food',
 'European, French, North Indian',
 'North Indian, Lucknowi, Afghan',
 'Fast Food, Italian, Desserts',
 'Continental, North Indian, Beverages',
 'Cafe, Mediterranean, Bakery, Greek',
 'South Indian, North Indian, Kerala, Seafood',
 'South Indian, North Indian, Biryani',
 'Asian, Japanese, Vietnamese, Korean, Chinese, Thai',
 'Continental, Asian, North Indian, Tea',
 'Tea, Beverages, Fast Food',
 'Seafood, Salad, North Indian, Biryani, Chinese',
 'Continental, European, BBQ, Chinese, Asian',
 'Fast Food, Street Food, Momos',
 'Cafe, Beverages',
 'North Indian, Chinese, Biryani, Beverages',
 'Cafe, Continental, American, Italian',
 'Andhra, South Indian, Biryani, North Indian, Mangalorean',
 'Fast Food, South Indian, Biryani',
 'Fast Food, Continental, Desserts',
 'Biryani, Hyderabadi, Kebab',
 'Biryani, South Indian, North Indian, Chinese',
 'South Indian, Biryani, North Indian, Chinese',
 'Bengali, Chinese, North Indian, Seafood',
 'Fast Food, Chinese, Burger, Hot dogs',
 'North Indian, South Indian, Juices',
 'Cafe, Salad, Wraps, Beverages',
 'North Indian, South Indian, Chinese, Beverages, Fast Food',
 'Juices, Ice Cream',
 'Continental, South Indian, North Indian, Asian',
 'Street Food, North Indian, Rolls',
 'Cafe, Salad, Healthy Food, Mexican',
 'Chinese, Asian, Momos',
 'Hyderabadi, North Indian, South Indian, Biryani',
 'Cafe, Pizza, Fast Food, Beverages',
 'South Indian, North Indian, Fast Food',
 'American, Tex-Mex, Burger, BBQ',
 'Beverages, Fast Food, Bakery',
 'North Indian, Chinese, Fast Food, Street Food',
 'North Indian, Mughlai, Chinese, South Indian, Mangalorean',
 'North Indian, Continental, Street Food',
 'North Indian, Thai, Japanese, Continental, Cafe',
 'Seafood, Andhra',
 'Beverages, Juices, Healthy Food',
 'North Indian, Afghan',
 'South Indian, Chinese, North Indian, Seafood',
 'Kerala, North Indian, Italian, Thai',
 'North Indian, Hyderabadi, Chinese, South Indian, Beverages, Desserts',
 'Cafe, Chinese, Pizza, North Indian, Burger',
 'North Indian, European, Mediterranean, BBQ',
 'South Indian, Chinese, North Indian, Sandwich, Rolls',
 'Fast Food, Tea, Beverages',
 'Chinese, Continental',
 'Continental, North Indian, South Indian, Italian',
 'Cafe, Coffee, Continental',
 'Andhra, Biryani',
 'Andhra, Seafood, Biryani',
 'African, Burger',
 'Fast Food, Burger, American',
 'Ice Cream, Beverages',
 'Sandwich, Rolls, South Indian, Ice Cream',
 'South Indian, Healthy Food',
 'Ice Cream, Desserts, Rolls',
 'Salad, Greek, Mediterranean',
 'North Indian, Kebab',
 'Bihari, North Indian, Chinese',
 'Italian, Mediterranean',
 'Desserts',
 'Mangalorean, Seafood, South Indian, North Indian, Chinese, Mughlai',
 'North Indian, Chinese, Rolls, Juices',
 'South Indian, North Indian, Chinese, Kerala',
 'Biryani, Hyderabadi, Chinese',
 'Chinese, Biryani',
 'Biryani, North Indian, Italian, Chinese, Sandwich, Desserts',
 'North Indian, Street Food, Biryani',
 'Street Food, Chinese, Fast Food',
 'Mediterranean, Continental, North Indian, Mughlai, Salad',
 'Cafe, Tea, Beverages, Fast Food',
 'North Indian, Continental, South Indian, Asian',
 'Chinese, Momos, Seafood',
 'North Indian, Steak, South Indian',
 'Bakery, Desserts, Healthy Food',
 'South Indian, Fast Food, Chinese',
 'Biryani, Chinese, North Indian, Seafood',
 'American, BBQ',
 'Thai, Momos',
 'Pizza, Continental, North Indian, Asian',
 'Bengali, Rolls, Chinese',
 'Andhra',
 'Beverages, Desserts',
 'North Indian, Fast Food, Street Food',
 'Chinese, North Indian, Kerala, Seafood, Fast Food',
 'Biryani, Rolls, Middle Eastern, Arabian, Charcoal Chicken',
 'Arabian, Biryani, North Indian',
 'Biryani, Chinese, Fast Food, Kebab',
 'Mangalorean, Chinese, North Indian',
 'Kebab, North Indian, Arabian, Chinese',
 'North Indian, Chinese, Biryani, Andhra, Mangalorean',
 'Seafood, North Indian',
 'Beverages, Italian, Pizza, Burger',
 'Continental, Burger, Pizza, Steak',
 'Chinese, Kerala, North Indian, South Indian',
 'Vietnamese, Salad',
 'Beverages, Juices, Fast Food',
 'Fast Food, North Indian, Chinese, Mughlai, Rolls',
 'Gujarati',
 'South Indian, Biryani, Chettinad, Juices',
 'North Indian, Seafood, Chinese, Biryani',
 'Cafe, Sandwich, Beverages',
 'North Indian, BBQ, Biryani, Kebab',
 'Cafe, Burger, Rolls, Beverages',
 'North Indian, Fast Food, Biryani, Chinese',
 'Chinese, Indonesian, Japanese, Malaysian, Thai, Vietnamese, Momos',
 'American, Modern Indian, Italian, South Indian',
 'Chinese, Cafe, Italian',
 'Street Food, Burger, Fast Food',
 'Fast Food, Mithai',
 'Cafe, Burger, Sandwich, Beverages',
 'Spanish, Italian, Mediterranean, European, Salad',
 'South Indian, Fast Food, Chinese, North Indian',
 'Chinese, Continental, North Indian, South Indian, Arabian',
 'Chinese, Thai, Seafood',
 'Andhra, Chinese, Continental',
 'Cafe, Fast Food, Desserts',
 'Arabian, North Indian, Chinese, Salad, Beverages',
 'BBQ, Continental, North Indian, Pizza, European',
 'North Indian, Hyderabadi, Chinese',
 'Lebanese, Turkish',
 'Chinese, Seafood, Momos',
 'Chinese, South Indian, Biryani',
 'Chinese, Andhra',
 'Cafe, Healthy Food, South Indian',
 'Beverages, Cafe, Desserts, Spanish, Bakery',
 'Beverages, Desserts, Fast Food',
 'Kerala, South Indian, Fast Food',
 'Healthy Food',
 'North Indian, Chinese, South Indian, Street Food',
 'South Indian, North Indian, Continental',
 'Healthy Food, Beverages, Cafe',
 'Andhra, Hyderabadi, Chinese',
 'Seafood, Mangalorean, Kerala',
 'Beverages, Juices, Fast Food, Rolls',
 'North Indian, Chinese, Kebab, Beverages',
 'Fast Food, Bengali, Rolls',
 'Street Food, Burger, Beverages, Fast Food, Sandwich, Finger Food',
 'Fast Food, Beverages, Momos',
 'South Indian, Chinese, North Indian, Desserts, Continental',
 'North Indian, Chinese, Arabian, Kebab',
 'European, Continental, Asian, Finger Food',
 'Continental, Finger Food',
 'Continental, American, Pizza, North Indian, Chinese, Finger Food, Asian, Thai',
 'South Indian, Street Food, Fast Food, Desserts, Beverages',
 'North Indian, Lucknowi, Mughlai, Biryani',
 'Chinese, North Indian, Fast Food, Street Food, Desserts',
 'Continental, North Indian, Italian, South Indian, Finger Food',
 'Mughlai, Kebab, Chinese',
 'North Indian, South Indian, Bengali',
 'Rajasthani, North Indian, Chinese',
 'North Indian, Chinese, Continental, Thai, Salad',
 'Fast Food, Beverages, Desserts',
 'Desserts, Beverages, Fast Food, Ice Cream',
 'Burger, American, Beverages, Desserts, Italian, Salad, Ice Cream, Finger Food',
 'Cafe, Chinese, Arabian',
 'Cafe, Italian, European',
 'Finger Food, Chinese, Continental',
 'Biryani, Seafood, Chinese, Charcoal Chicken',
 'Biryani, Chinese, South Indian',
 'Cafe, Continental, North Indian',
 'American, European',
 'Chinese, Sushi, Asian, Thai',
 'Fast Food, Sandwich, Salad, Healthy Food',
 'South Indian, Chettinad, Chinese, North Indian, Andhra, Seafood',
 'Cafe, Fast Food, Pizza, Burger, Beverages',
 'Chinese, Italian, Fast Food, Momos',
 'Desserts, Beverages, Ice Cream',
 'Continental, Italian, North Indian, Chinese',
 'Continental, South Indian, North Indian, Arabian',
 'Rolls, North Indian, Chinese, Biryani',
 'Chinese, North Indian, Hyderabadi, Biryani',
 'Arabian, BBQ, Biryani, Chinese, Continental, Ice Cream, North Indian, South Indian',
 'Finger Food, Continental, North Indian, Pizza, Burger',
 'Arabian, Kerala, North Indian, Chinese, Beverages',
 'North Indian, Biryani, Rolls, Beverages',
 'Fast Food, South Indian, North Indian',
 'Kerala, North Indian, Chinese, Hyderabadi, Arabian',
 'Biryani, Chinese, North Indian',
 'Seafood, Biryani, South Indian, North Indian, Rolls',
 'Andhra, North Indian, Chinese, Seafood, Biryani',
 'Ice Cream, Cafe, Pizza, Burger, Desserts, Beverages',
 'North Eastern, Street Food',
 'Biryani, Kebab, Rolls, Mughlai',
 'Kebab, North Indian, Fast Food, Beverages',
 'Italian, Salad, Healthy Food, Cafe, Asian, Desserts, Pizza',
 'South Indian, Street Food, Fast Food',
 'Ice Cream, Fast Food',
 'Burger, Beverages, Rolls',
 'North Indian, Kebab, Seafood, Chinese',
 'Healthy Food, North Indian, Biryani, Continental, Desserts',
 'North Indian, Chinese, South Indian, Biryani',
 'Thai, Vietnamese, Asian, Chinese',
 'North Indian, Arabian, Fast Food, Chinese',
 'Biryani, Mangalorean, Kerala',
 'BBQ',
 'North Indian, Mughlai, Rolls, Fast Food',
 'Finger Food, American, Asian, Italian',
 'Continental, Asian, American, North Indian, Desserts',
 'North Indian, Seafood, Biryani, Chinese',
 'Cafe, Continental, Sandwich',
 'North Indian, Chinese, Fast Food, Beverages, Desserts',
 'North Indian, Chinese, Continental, Pizza',
 'Biryani, Andhra, Kebab',
 'North Indian, Chinese, South Indian, Continental',
 'Asian, BBQ, Seafood, Chinese',
 'Italian, Chinese, Continental, North Indian',
 'Continental, North Indian, South Indian, Mangalorean',
 'Hyderabadi, Biryani',
 'South Indian, Kerala, Andhra',
 'BBQ, North Indian, Continental, Chinese',
 'Arabian, Chinese, North Indian, Kerala, Juices',
 'Asian, BBQ, South Indian, Chinese',
 'Street Food, Juices',
 'Andhra, North Indian, South Indian',
 'South Indian, Kerala, Chinese',
 'Chinese, Finger Food, North Indian, Seafood',
 'Cafe, Italian, Continental, Beverages',
 'Bakery, Fast Food, Burger, Rolls, Beverages',
 'Bakery, Fast Food, Desserts, Beverages',
 'Kerala, Chinese, South Indian, North Indian',
 'Continental, North Indian, Chinese, European, BBQ, Finger Food, Asian',
 'Andhra, Biryani, North Indian, Chinese',
 'Chinese, South Indian, North Indian',
 'Mangalorean, Seafood, Chinese, Biryani',
 'Asian, Chinese, Thai, Seafood, Momos',
 'North Indian, Modern Indian',
 'Biryani, Italian, BBQ',
 'Healthy Food, Sandwich',
 'Cafe, Burger',
 'Chinese, Italian, North Indian',
 'Continental, North Indian, Chinese, Pizza',
 'Cafe, Healthy Food, Salad, Beverages, Desserts',
 'American, Italian',
 'Fast Food, Continental, Italian, Rolls, Sandwich',
 'Continental, North Indian, South Indian, Chinese',
 'Biryani, Kebab, South Indian',
 'South Indian, Fast Food, Juices',
 'Desserts, Bakery',
 'North Indian, Mithai',
 'Continental, Biryani, Desserts, Italian, North Indian, Chinese, Modern Indian, Asian',
 'BBQ, Chinese, Japanese, Asian',
 'North Indian, South Indian, Fast Food, Momos',
 'Vietnamese',
 'Cafe, Bakery, Beverages',
 'Desserts, Juices, Fast Food',
 'Chinese, Naga',
 'North Indian, Street Food, Mithai',
 'Continental, Chinese, North Indian, South Indian',
 'Fast Food, North Indian, Street Food',
 'Momos, Street Food, Rolls',
 'Juices, Sandwich, Burger, Beverages, Continental',
 'North Indian, Chinese, South Indian, Seafood',
 'European, Spanish, Continental, Italian',
 'Ice Cream, Juices, Fast Food',
 'Asian, Continental, Mediterranean, Salad, American, Biryani',
 'Chinese, Street Food, Ice Cream',
 'North Indian, Chinese, Thai',
 'Arabian, North Indian, Biryani, Chinese, Seafood',
 'Cafe, North Indian, Chinese',
 'South Indian, Seafood, Rolls, Beverages',

In [82]:
#cuisines → Replace NaN with "Other"
df["cuisines"]=df["cuisines"].replace(np.nan,"Other")
df["cuisines"].isna().sum()

0

In [83]:
set(df["rest_type"])

{'Bakery',
 'Bakery, Beverage Shop',
 'Bakery, Cafe',
 'Bakery, Dessert Parlor',
 'Bakery, Food Court',
 'Bakery, Kiosk',
 'Bakery, Quick Bites',
 'Bakery, Sweet Shop',
 'Bar',
 'Bar, Cafe',
 'Bar, Casual Dining',
 'Bar, Lounge',
 'Bar, Pub',
 'Bar, Quick Bites',
 'Beverage Shop',
 'Beverage Shop, Cafe',
 'Beverage Shop, Dessert Parlor',
 'Beverage Shop, Quick Bites',
 'Bhojanalya',
 'Cafe',
 'Cafe, Bakery',
 'Cafe, Bar',
 'Cafe, Casual Dining',
 'Cafe, Dessert Parlor',
 'Cafe, Food Court',
 'Cafe, Lounge',
 'Cafe, Quick Bites',
 'Casual Dining',
 'Casual Dining, Bar',
 'Casual Dining, Cafe',
 'Casual Dining, Irani Cafee',
 'Casual Dining, Lounge',
 'Casual Dining, Microbrewery',
 'Casual Dining, Pub',
 'Casual Dining, Quick Bites',
 'Casual Dining, Sweet Shop',
 'Club',
 'Club, Casual Dining',
 'Confectionery',
 'Delivery',
 'Dessert Parlor',
 'Dessert Parlor, Bakery',
 'Dessert Parlor, Beverage Shop',
 'Dessert Parlor, Cafe',
 'Dessert Parlor, Food Court',
 'Dessert Parlor, Kiosk',
 'Dessert Parlor, Quick Bites',
 'Dessert Parlor, Sweet Shop',
 'Dhaba',
 'Fine Dining',
 'Fine Dining, Bar',
 'Fine Dining, Lounge',
 'Fine Dining, Microbrewery',
 'Food Court',
 'Food Court, Beverage Shop',
 'Food Court, Casual Dining',
 'Food Court, Dessert Parlor',
 'Food Court, Quick Bites',
 'Food Truck',
 'Kiosk',
 'Lounge',
 'Lounge, Bar',
 'Lounge, Cafe',
 'Lounge, Casual Dining',
 'Lounge, Microbrewery',
 'Mess',
 'Mess, Quick Bites',
 'Microbrewery',
 'Microbrewery, Bar',
 'Microbrewery, Casual Dining',
 'Microbrewery, Lounge',
 'Microbrewery, Pub',
 'Pop Up',
 'Pub',
 'Pub, Bar',
 'Pub, Cafe',
 'Pub, Casual Dining',
 'Pub, Microbrewery',
 'Quick Bites',
 'Quick Bites, Bakery',
 'Quick Bites, Beverage Shop',
 'Quick Bites, Cafe',
 'Quick Bites, Dessert Parlor',
 'Quick Bites, Food Court',
 'Quick Bites, Kiosk',
 'Quick Bites, Meat Shop',
 'Quick Bites, Mess',
 'Quick Bites, Sweet Shop',
 'Sweet Shop',
 'Sweet Shop, Dessert Parlor',
 'Sweet Shop, Quick Bites',
 'Takeaway',
 'Takeaway, Delivery',
 nan}

In [84]:
#rest_type → Replace NaN with "Unknown"
df["rest_type"]=df["rest_type"].replace(np.nan,"Other")
df["rest_type"].isna().sum()

0

### Step 4: Votes Column
- Fill missing values in votes with median

**There are no missing values to fill in "votes" column**

In [85]:
set(df["votes"])

{0,
 1,
 2,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 637,
 638,
 639,
 641,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 807,
 808,
 809,
 811,
 813,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 8304,
 825,
 826,
 827,
 829,
 9021,
 830,
 832,
 833,
 834,
 835,
 836,
 837,
 840,
 841,
 842,
 843,
 845,
 847,
 848,
 9041,
 850,
 851,
 853,
 854,
 856,
 857,
 858,
 859,
 860,
 861,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 9064,
 873,
 872,
 875,
 874,
 876,
 877,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 9080,
 891,
 892,
 893,
 894,
 895,
 890,
 897,
 9084,
 9085,
 900,
 901,
 902,
 903,
 904,
 905,
 898,
 907,
 908,
 909,
 910,
 911,
 912,
 914,
 915,
 917,
 918,
 919,
 920,
 922,
 923,
 924,
 926,
 927,
 929,
 930,
 932,
 933,
 935,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 949,
 950,
 951,
 952,
 953,
 954,
 956,
 957,
 958,
 960,
 961,
 962,
 964,
 965,
 966,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 991,
 992,
 994,
 995,
 996,
 997,
 998,
 1000,
 1003,
 1004,
 1007,
 1008,
 1010,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1030,
 1031,
 1033,
 1034,
 1036,
 1037,
 1038,
 1042,
 1043,
 1045,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 ...}

In [86]:
df["votes"].isna().sum()
#There are no missing values to fill in "votes" column

0

### Step 5: Binary Encoding
- Convert the following binary fields:
- Column             Mapping

 online_order    Yes → 1, No → 0
 
 book_table      Yes → 1, No → 0

In [87]:
set(df["online_order"])

{'No', 'Yes'}

In [88]:
#online_order Yes → 1, No → 0
df["online_order"]=df["online_order"].replace("Yes",1)
df["online_order"]=df["online_order"].replace(["NO","No"],0)
set(df["online_order"])

{0, 1}

In [89]:
set(df["book_table"])

{'No', 'Yes'}

In [90]:
#book_table Yes → 1, No → 0
df["book_table"]=df["book_table"].replace("Yes",1)
df["book_table"]=df["book_table"].replace("No",0)
set(df["online_order"])

{0, 1}

### Step 6: Data Type Conversion
- Ensure the following conversions:
- rate → float


- votes → integer


- approx_costfor_two_people → integer

In [91]:
# rate → float
df["rate"].dtype

dtype('float64')

In [92]:
# votes → integer
df["votes"].dtype

dtype('int64')

In [93]:
# approx_costfor_two_people → integer
df["approx_costfor_two_people"].dtype

dtype('float64')

In [94]:
df["approx_costfor_two_people"]= df["approx_costfor_two_people"].astype(int)

In [95]:
df["approx_costfor_two_people"].dtype

dtype('int32')

In [96]:
print(".info()")
print("==========================================================")
print(df.info())
print(".describe")
print("==========================================================")
print(df.describe())
print(".isnull().sum()")
print("==========================================================")
print(df.isnull().sum())

.info()
==========================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   online_order               51717 non-null  int64
 1   book_table                 51717 non-null  int64
 2   rate                       51717 non-null  float64
 3   votes                      51717 non-null  int64
 4   rest_type                  51717 non-null  object
 5   dish_liked                 51717 non-null  object
 6   cuisines                   51717 non-null  object
 7   approx_costfor_two_people  51717 non-null  int32
 8   listed_intype              51717 non-null  object
 9   listed_incity              51717 non-null  object
dtypes: float64(1), int32(1), int64(3), object(5)
memory usage: 3.7+ MB
None
.describe
==========================================================
       online_order    book_table          rate         votes  \
count  51717.000000  51717.000000  51717.000000  51717.000000
mean       0.588665      0.124698      3.700362    283.697527
std        0.492080      0.330379      0.395391    803.838853
min        0.000000      0.000000      1.800000      0.000000
25%        0.000000      0.000000      3.500000      7.000000
50%        1.000000      0.000000      3.700000     41.000000
75%        1.000000      0.000000      3.900000    198.000000
max        1.000000      1.000000      4.900000  16832.000000

       approx_costfor_two_people
count               51717.000000
mean                  554.391689
std                   437.563723
min                    40.000000
25%                   300.000000
50%                   400.000000
75%                   650.000000
max                  6000.000000
.isnull().sum()
==========================================================
online_order                 0
book_table                   0
rate                         0
votes                        0
rest_type                    0
dish_liked                   0
cuisines                     0
approx_costfor_two_people    0
listed_intype                0
listed_incity                0
dtype: int64

# # Geospatial  dataset

In [97]:

df1=pd.read_csv(r"C:\Users\rajashekar\OneDrive\Desktop\HAckathon\Geographical Coordinates.csv")

In [98]:
df1

            listed_incity   Latitude  Longitude
0            Banashankari  12.939333  77.553982
1       Bannerghatta Road  12.952660  77.605048
2            Basavanagudi  12.941726  77.575502
3               Bellandur  12.925352  77.675941
4            Brigade Road  12.967358  77.606435
5             Brookefield  12.963814  77.722437
6                     BTM  12.916360  77.604733
7           Church Street  12.974914  77.605247
8         Electronic City  12.848760  77.648253
9             Frazer Town  12.998683  77.615525
10                    HSR  12.900563  77.649475
11            Indiranagar  12.996298  77.545278
12              Jayanagar  12.939904  77.582638
13               JP Nagar  12.909694  77.586607
14           Kalyan Nagar  13.022142  77.640337
15           Kammanahalli  13.014854  77.638203
16  Koramangala 4th Block  12.932778  77.629405
17  Koramangala 5th Block  12.934843  77.618977
18  Koramangala 6th Block  12.939025  77.623848
19  Koramangala 7th Block  12.936485  77.613478
20           Lavelle Road  12.968340  77.596507
21           Malleshwaram  13.002735  77.570325
22           Marathahalli  12.955257  77.698416
23                MG Road  12.975526  77.606790
24           New BEL Road  13.039186  77.564284
25       Old Airport Road  12.960632  77.642500

- merging can be done using merge functionm,
- we can see that both the dastsets share a same column called"listed_incity"

In [99]:
df2=df.merge(df1,on="listed_incity")

In [100]:
df2

,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_costfor_two_people,listed_intype,listed_incity,Latitude,Longitude
0,1,1,4.1,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,12.939333,77.553982
1,1,0,4.1,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,12.939333,77.553982
2,1,0,3.8,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,12.939333,77.553982
3,0,0,3.7,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,12.939333,77.553982
4,0,0,3.8,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,12.939333,77.553982
...,...,...,...,...,...,...,...,...,...,...,...,...
46132,0,1,4.1,146,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European",1200,Pubs and bars,Old Airport Road,12.960632,77.642500
46133,0,0,3.1,11,Bar,Not Available,"North Indian, Chinese",1000,Pubs and bars,Old Airport Road,12.960632,77.642500
46134,0,1,3.7,0,"Bar, Casual Dining","Margarita, Churros, Cocktails, Wings, Murgh Gh...","Finger Food, Continental, North Indian, Fast Food",1600,Pubs and bars,Old Airport Road,12.960632,77.642500
46135,0,0,3.7,0,Casual Dining,Not Available,"European, Italian, Seafood, Continental",2100,Pubs and bars,Old Airport Road,12.960632,77.642500
46136,1,0,3.7,0,Pub,Not Available,"Finger Food, Salad, Chinese, Continental",1300,Pubs and bars,Old Airport Road,12.960632,77.642500

In [101]:
set(df2["listed_incity"])

{'BTM',
 'Banashankari',
 'Bannerghatta Road',
 'Basavanagudi',
 'Bellandur',
 'Brigade Road',
 'Brookefield',
 'Church Street',
 'Electronic City',
 'Frazer Town',
 'HSR',
 'Indiranagar',
 'JP Nagar',
 'Jayanagar',
 'Kalyan Nagar',
 'Kammanahalli',
 'Koramangala 4th Block',
 'Koramangala 5th Block',
 'Koramangala 6th Block',
 'Koramangala 7th Block',
 'Lavelle Road',
 'MG Road',
 'Malleshwaram',
 'Marathahalli',
 'New BEL Road',
 'Old Airport Road'}

# Exploratory Data Analysis -EDA

## 1. Counting the number of orders from each "liasted_incity"

In [102]:
g1=df2.groupby("listed_incity")["rest_type"].count()
g1

listed_incity
BTM                      3279
Banashankari              863
Bannerghatta Road        1617
Basavanagudi             1266
Bellandur                1227
Brigade Road             1769
Brookefield              1518
Church Street            1827
Electronic City          1229
Frazer Town              1185
HSR                      1741
Indiranagar              1860
JP Nagar                 2096
Jayanagar                2371
Kalyan Nagar             1309
Kammanahalli             1329
Koramangala 4th Block    2779
Koramangala 5th Block    2836
Koramangala 6th Block    2623
Koramangala 7th Block    2938
Lavelle Road             1744
MG Road                  1811
Malleshwaram             1096
Marathahalli             1659
New BEL Road              740
Old Airport Road         1425
Name: rest_type, dtype: int64

# removing nan values

In [103]:
df2=df2.dropna(subset=["Latitude","Longitude"])

In [109]:
import folium
from folium.plugins import HeatMap

In [110]:
bangalore_map = folium.Map(location=[12.9716, 77.5946], zoom_start=12)

restaurant_locations = df2[['Latitude', 'Longitude']].values.tolist()

HeatMap(restaurant_locations).add_to(bangalore_map)

bangalore_map.save("restaurant_density_map.html")

In [111]:
italian_df = df2[df2['cuisines'].str.contains("Italian", case=False, na=False)]

italian_map = folium.Map(location=[12.9716, 77.5946], zoomstart=12)

for  _, row in italian_df.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=row['rate'],
        icon=folium.Icon(color="red")
    ).add_to(italian_map)

italian_map.save("italian_restaurants_map.html")